### ISSUE TITLE
PDF tokilearning

### ISSUE THREAD

**Issue by hockyy** [ia-toki/ia-toki.github.io#3]
![screenshot 49](https://cloud.githubusercontent.com/assets/19528709/15465992/9a5e95da-2101-11e6-8322-a91957017140.png)
![screenshot 50](https://cloud.githubusercontent.com/assets/19528709/15465996/9d3b9fb4-2101-11e6-8fc5-b2b1cc6676b9.png)
contoh kode bubble sort dan insertion sort salah.

**Comment by gyosh** [comment]
@hockyy Terima kasih atas laporannya, sudah diperbaiki.
Ngomong2, seharusnya isu ditulis di repository training-gate-id: https://github.com/ia-toki/training-gate-id/issues/new

Bisa tolong tuliskan kembali isunya di sana?
